### buscar ids
GET http://localhost:3000/user/

### buscar Id unico
GET http://localhost:3000/user/82a03a9e-fb73-4450-b4b6-171fb2717ed1

### inserir user

POST http://localhost:3000/user/
content-type: application/json

{
    "name": "nome",
    "email": "email.gg@gmail.com"
}

### deletar user
delete http://localhost:3000/user/82a03a9e-fb73-4450-b4b6-171fb2717ed1

### Atualizar um usuario pelo ID
PUT  http://localhost:3000/user/f82227d7-5253-4855-a576-7e3ddcf8364b
content-type: application/json

{
    "name": "nome2",
    "email": "email2.gg@gmail.com"
}

### buscar Ids pela rota USER
GET http://localhost:3000/user/
