### Test conexão
GET https://3000-williamschr-projectback-u5njcs4hg69.ws-us90.gitpod.io

### Test post

POST https://3000-williamschr-projectback-u5njcs4hg69.ws-us90.gitpod.io
content-type: application/json

{
    "name": "nome",
    "email": "email.gg@gmail.com"
}
